using System.Collections.Generic;

namespace OnlineBanking.BL
{
    public enum ECategory
    {
          Car                   = 139              ,
          Travel                = 140	             ,    
          Children              = 141	             ,    
          Drugstore             = 143	             ,    
          HouseAndGarden        = 144	             ,            
          Electronics           = 145	             ,        
          FoodAndDrink          = 147	             ,        
          Beauty                = 148	             ,    
          Culture               = 149	             ,    
          Fashion               = 150	             ,    
          Groceries             = 151	             ,    
          FinancialServices     = 152	             ,            
          FreeTime              = 154	             ,    
          Health                = 155	             ,    
          ConsumerGoods         = 156	             ,        
          Atm                   = 99999	         ,
          Pets                  = 178774	         ,
          ShoppingOnline        = 1483997	         ,            
          ProfessionalServices  = 1483998	         ,                
          DigitalServices       = 1484001	         ,            
          BillsAndHousehold     = 1484005	         ,            
          Sport                 = 3653021,           

    }

    public enum ShopType
    {
        MERCHANT, 
        ATM,
        ONLINE
    }
    
    public enum EGender
    {
        Female,
        Male
    }

    public static class Constants
    {
        public static HashSet<string> Tags = new HashSet<string>()
        {
"Accommodation Booking", 
"Accommodations", 
"Administrative Fees", 
"Advertising / Marketing", 
"Aesthetic Medicine", 
"Air Conditioning", 
"Airport Lounge", 
"Air Tickets", 
"Alcohol", 
"Alternative Medicine", 
"American Cuisine", 
"American Fast Food", 
"Apple", 
"Aquarium And Fish Breeding", 
"Arabic Cuisine", 
"Arabic Deli", 
"Art Supplies", 
"Asian Cuisine", 
"Asian Deli", 
"Atm-All", 
"Audiobooks", 
"Audio Technics", 
"Aviation", 
"Bageterie", 
"Bakery", 
"Balkan Cuisine", 
"Bank", 
"Bar", 
"Barber Shop", 
"Bathing Suit", 
"Bathrooms", 
"Beauty", 
"Beauty - Goods", 
"Beauty Salon", 
"Beauty Service", 
"Bedroom", 
"Beer-Cellar", 
"Beer / Cider", 
"Bijouterie", 
"Bike", 
"Bike Rentals", 
"Bike Service", 
"Bikesharing", 
"Billiards", 
"Bio Drugstore", 
"Bio, Healthy Food And Farm Products", 
"Blinds/Awnings", 
"Board Games", 
"Board/Skate Shop", 
"Bobsled Track", 
"Bonus Program", 
"Bookstore", 
"Bowling", 
"Building Supply Store", 
"Bus", 
"Butcher Shop", 
"Cafe", 
"Cameras And Accessories", 
"Camp", 
"Cannabis", 
"Canoe Equipment", 
"Carpool", 
"Car Rentals", 
"Car Repair Shop", 
"Car Sales", 
"Car Services", 
"Carsharing", 
"Car - Verification Of Origin", 
"Car - Washing", 
"Castles And Palaces", 
"Catering", 
"Ceramics", 
"Cheese", 
"Children Clothing", 
"Childrens Equipment", 
"Children Shoes", 
"Child Services", 
"Cinema", 
"Cleaners", 
"Climbing", 
"Clinic", 
"Clothing - Other", 
"CNG", 
"Coffee", 
"Collecting", 
"Concerts", 
"Confectionery Supplies", 
"Construction Industry", 
"Consumer Goods - Mix", 
"Cooking Courses", 
"Cosmetics / Perfumery", 
"Counselling, Consultation", 
"Coworking Space", 
"Creperie", 
"Cryptocurrencies", 
"Custom Clothing", 
"Custom Furniture", 
"Czech Restaurant", 
"Dairy", 
"Dance", 
"Dance Needs", 
"Data Storage", 
"Dating Site", 
"Decoration", 
"Delicatessen And Specialized Stores", 
"Delivery Service", 
"Dental Care", 
"Dentistry", 
"Department Store", 
"Dermatology", 
"Diet", 
"Dietary Supplements", 
"Discount Portal", 
"Discount Store", 
"Distillates", 
"Diving", 
"Donation And Crowdfunding", 
"Door", 
"Drinking", 
"Driving School", 
"Drugstore", 
"E-Books", 
"Education", 
"Electrical Parts / Wiring", 
"Electric Scooters", 
"Electronics Goods", 
"Electronics Service", 
"Equipment Cosmetics, Manicure, Pedicure, Hairdresser", 
"Erotic Goods", 
"Eshop With Everything", 
"Esotericism", 
"Events / Activities For Kids", 
"Exchange Office", 
"Excursions And Tourist Attractions", 
"Exhibition", 
"Experiences", 
"Fabrics/Textiles", 
"Fanshop", 
"Farmers Equipment", 
"Fashion Accessories", 
"Fashion Chain - Mix", 
"Festival", 
"Fish", 
"Fishing", 
"Fitness / Bodybuilding", 
"Floorball", 
"Floors And Carpets", 
"Floor Tiles", 
"Florists", 
"Food - Order", 
"Football", 
"Footwear", 
"Foreign", 
"Formal Clothes", 
"Freetime Activity", 
"Free Time Mix", 
"Fresh Bar", 
"Frozen Food", 
"Fruit/Vegetables", 
"Furniture", 
"Gambling And Betting", 
"Gaming Electronics", 
"Garden", 
"Garden Architecture", 
"Garden centre", 
"Garden Equipment", 
"Garden Furniture", 
"Gas And Electricity", 
"Gas Station", 
"Gay", 
"General Practitioner", 
"Gifts", 
"Glass", 
"Golf", 
"Golf Equipment", 
"Gourmet", 
"Greek Deli", 
"Groceries - Other", 
"Gynecology", 
"Haberdashery", 
"Hairdressers", 
"Handbags", 
"Hats", 
"Health Supplies", 
"Healthy Fast Food", 
"Healthy Lifestyle", 
"Herbs", 
"Hobby Shop", 
"Hockey", 
"Home Accessories", 
"Home Textiles", 
"Horses And Equestrian Equipment", 
"Hospital", 
"Hotels And Guesthouses", 
"House And Garden", 
"Household Electronics", 
"Household Equipment", 
"Household Goods", 
"Household Water", 
"Hyper-Supermarket", 
"Ice Cream", 
"Indian Restaurant", 
"Infant", 
"Insurance", 
"Irish Pub", 
"Ironmongery", 
"Italian Deli", 
"Italian Restaurant / Pizzeria", 
"IT Services", 
"Jewellery", 
"Kitchen", 
"Language Courses", 
"Laser Game", 
"Leather Haberdashery", 
"Library", 
"Lights", 
"Loan", 
"Local Transport", 
"Locksmithery", 
"Logistics", 
"Long Distance Transport", 
"LPG", 
"Luxury", 
"Maps", 
"Martial Arts", 
"Massage", 
"Mediterranean Cuisine", 
"Mens Clothing", 
"Metal", 
"Mexican Restaurant", 
"Micromobility", 
"Mobile And Data Services", 
"Mobile Phones And Accessories", 
"Mobile Service", 
"Modeling", 
"Motorbike", 
"Motorcycle Accessories", 
"Mot - State Vehicle Inspection", 
"Movies", 
"Movies / Games / Music", 
"Music", 
"Musical Instruments", 
"Music Club", 
"Musli", 
"Natural Cosmetics", 
"Navigation", 
"News Stand", 
"Night Club", 
"Nuts", 
"Observatory", 
"Office Supplies", 
"Online Beauty", 
"Online Bills And Household", 
"Online Car", 
"Online Children", 
"Online Consumer Goods", 
"Online Culture", 
"Online Digital Services", 
"Online Drugstore", 
"Online Electronics", 
"Online Fashion", 
"Online Financial Services", 
"Online Food And Drink", 
"Online Freetime", 
"Online Groceries", 
"Online Health", 
"Online House And Garden", 
"Online / PC Games", 
"Online Pets", 
"Online Pharmacy", 
"Online Professional Services", 
"Online Sport", 
"Online Travel", 
"Ophthalmologist", 
"Optics And Optical Services", 
"Orthopedics", 
"Outdoor Equipment", 
"Paintball", 
"Paints Varnishes", 
"Pantyhose / Socks", 
"Parking", 
"Parties And Celebrations", 
"Pasta", 
"Payment Gateway", 
"Pc And Accessories", 
"Pc Service", 
"Pet Care", 
"Pets", 
"Pet Supplies", 
"Pharmacy", 
"Photo Printing", 
"Photo / Video Service", 
"Porn", 
"Printing / Copying", 
"Proctology", 
"Professional Services", 
"Public Transport", 
"Real Estate Sale And Lease", 
"Reconstruction", 
"Recurring Payment", 
"Rehabilitation", 
"Religion", 
"Reproductive Medicine", 
"Restaurant", 
"Restaurant Without A Waiter", 
"Retirement Home", 
"Rheumatology", 
"Road Charges", 
"Romanian Restaurant", 
"Running Equipment", 
"Russian Deli", 
"Sale Of Swimming Pools/Saunas ", 
"Sauna", 
"School Supplies", 
"Scientific Center", 
"Second Hand", 
"Service Of Household Appliances", 
"Services - Mix", 
"Ships", 
"Shirt", 
"Shoe Repair", 
"Shopping Online", 
"Ski", 
"Ski Areal", 
"Slovak Restaurant", 
"Software / Applications", 
"Solarium", 
"South American Cuisine", 
"Spare Parts - Accessories", 
"Spices", 
"sport", 
"Sports And Outdoor Equipment", 
"Sports Events / Races", 
"Sports Field", 
"Sportswear", 
"Stationery", 
"Steak House / Burgers", 
"Stock Market Trading", 
"Subscription", 
"Subscription - Press And Media", 
"Suitcases/Bags", 
"Sunglasses", 
"Sushi", 
"Sustainable", 
"Sweets", 
"Sweetshop", 
"Swimming", 
"Taxi", 
"Tea", 
"Tearoom", 
"Tennis", 
"Tennis / Badminton / Squash", 
"Theater", 
"Tickets-Booking", 
"Ties", 
"Tire Service", 
"Tobacco And Smoking Supplies", 
"Tools", 
"Toys", 
"Train", 
"Transport Service", 
"Travel Agency", 
"Turkish Cuisine", 
"Underwear", 
"Unknown", 
"Used Car Dealer/Mart", 
"Various Digital Services", 
"Various Financial Services", 
"Vegetarian / Vegan", 
"Vegetarian / Vegan Restaurant", 
"Vending Machine", 
"Veterinary", 
"Visas And Permits", 
"Watchmakers", 
"Water Filtration", 
"Water Park", 
"Weapons And Ammunition", 
"Webhosting", 
"Wedding", 
"Wellness", 
"Wine", 
"Wine Cellar", 
"Wine Supplies", 
"Womens Clothing", 
"Wood", 
"Work Clothes", 
"Yoga", 
"Zero Waste", 
"Zoo"
        };
    }
}

